# Generated by Django 5.2.4 on 2025-08-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerseasonstats",
            old_name="red_cards",
            new_name="red_card",
        ),
        migrations.RenameField(
            model_name="playerseasonstats",
            old_name="yellow_cards",
            new_name="yellow_card",
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
