# Generated by Django 5.2.4 on 2025-09-08 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerseasonstats",
            old_name="fouls_commited",
            new_name="aerial_duels_lost",
        ),
        migrations.AddField(
            model_name="goalkeeper",
            name="crosses_stopped",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goalkeeper",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="league_of_goalkeeper",
                to="api.league",
            ),
        ),
        migrations.AddField(
            model_name="goalkeeper",
            name="passes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goalkeeper",
            name="pen_saved",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goalkeeper",
            name="psxg_performance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goalkeeper",
            name="sweeper_action",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goalkeeper",
            name="sweeper_action_per90",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="aerial_duels_won",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="ball_recoveries",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="blocks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="dispossessed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="fouls_committed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="league_of_player",
                to="api.league",
            ),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="matches_completed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="matches_substituted",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="miscontrols",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="npxg_performance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="offsides",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="pass_switches",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="pen_conceded",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="pen_won",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="prog_carries_final_3rd",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="prog_passes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="through_ball",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="unused_sub",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="xg_performance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goalkeeper",
            name="position",
            field=models.CharField(default="GK", max_length=20),
        ),
    ]
