# Generated by Django 5.2.4 on 2025-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_red_cards_playerseasonstats_red_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="code",
            field=models.CharField(default="null", max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goalkeeper",
            name="position",
            field=models.CharField(blank=True, default="GK", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="league",
            name="total_clubs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="fouls_commited",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="fouls_won",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
