# Generated by Django 5.2.4 on 2025-09-08 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0002_rename_fouls_commited_playerseasonstats_aerial_duels_lost_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalkeeper",
            name="league",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="league_of_goalkeeper",
                to="api.league",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playerseasonstats",
            name="league",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="league_of_player",
                to="api.league",
            ),
            preserve_default=False,
        ),
    ]
