# Generated by Django 5.2.4 on 2025-09-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_goalkeeper_league_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AddConstraint(
            model_name="league",
            constraint=models.UniqueConstraint(
                fields=("country", "name"), name="unique_country_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("league", "season"), name="unique_league_season"
            ),
        ),
    ]
