# Generated by Django 5.2.4 on 2025-09-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_country_code_goalkeeper_position_league_total_clubs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
