# Generated by Django 5.2.4 on 2025-09-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_club_name_league_unique_country_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clubseasonstat",
            old_name="passes",
            new_name="attempted_passes_against",
        ),
        migrations.RenameField(
            model_name="clubseasonstat",
            old_name="passes_comp",
            new_name="comp_passes_allowed",
        ),
        migrations.RenameField(
            model_name="clubseasonstat",
            old_name="passes_to_final_third",
            new_name="passes_to_final_third_allowed",
        ),
        migrations.RenameField(
            model_name="clubseasonstat",
            old_name="passes_to_pen_area",
            new_name="passes_to_pen_area_allowed",
        ),
        migrations.RenameField(
            model_name="clubseasonstat",
            old_name="shots",
            new_name="shots_allowed",
        ),
        migrations.RenameField(
            model_name="clubseasonstat",
            old_name="shots_target",
            new_name="shots_target_allowed",
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="take_ons_won",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
